linters:
  disable-all: true
  enable:
    - goimports
    - gofmt
    - ginkgolinter
    - golint
    - gocritic
    - goconst
    - gocyclo
    - gosimple
    - govet
    - errcheck
issues:
  exclude-use-default: false
